name: MainReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: yarn install, build, and test
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          yarn global add esbuild
          make ext
