name: MainReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: yarn install, build, and test
        run: |
          yarn global add esbuild
          make ext
